language: php

php:
  - 7.1.18

before_install:
  - '#### Phive ####'
  - wget https://phar.io/releases/phive.phar
  - wget https://phar.io/releases/phive.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/bin/phive

install:
  - bin/phing setup

before_script:
  - bin/phing cc:before-build

script:
  - bin/phing qa

after_script:
  - bin/phing cc:after-build

cache:
  directories:
    - /home/travis/.cache/composer
    - /home/travis/.phive
    - /home/travis/.gnupg
