# TravisCI configuration for jawira/case-converter

_shared_script_install_phive: &script_install_phive |
  # Install PHIVE (cached)
  if [ ! -r "${HOME}/.phive/phive.phar" ]; then
    mkdir -p "${HOME}/bin" "${HOME}/.phive"
    travis_retry wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
    travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
    travis_retry gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 \
      --recv-keys 0x9D8A98B29B2D5D79
    if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
      echo "Invalid phive signature" 1>&2
      rm -f "${HOME}/.phive/phive.phar"
      exit 11
    fi
    rm "${HOME}/.phive/phive.phar.asc"
  fi
  install --verbose --mode=0755 --no-target-directory -D "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
  export PATH="${HOME}/bin:${PATH}"

if: "branch = master"

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "7.4"
  - "7.3"
  - "7.2"

cache:
  directories:
    - "${HOME}/.phive"
    - "${HOME}/.composer/cache"

before_install:
  - *script_install_phive
  - "travis_retry \"${HOME}/bin/phive\" install --force-accept-unsigned --trust-gpg-keys 4AA394086372C20A,8E730BA25823D8B5,2420BAE0A3BE25C6,31C7E470E2138192,CF1A108D0E7AE720"

install:
  - "bin/phing setup"

before_script:
  - "bin/phing cc:before-build"

script:
  - "bin/phing qa"

after_script:
  - "bin/phing cc:after-build"
