language: php

php:
  - 7.1.18

before_install:
  - eval echo ~$USER
  - "echo '#### Phive ####'"
  - wget https://phar.io/releases/phive.phar
  - wget https://phar.io/releases/phive.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/bin/phive

install:
  - phive install
  - bin/phing setup

script:
  - bin/phing test

cache:
  directories:
    - /home/.cache/composer
    - /home/.phive
