language: php

php:
  - 7.1.18

before_script:
  - "echo '#### Phive ####'"
  - wget -O /usr/local/bin/phive https://phar.io/releases/phive.phar
  - chmod -x /usr/local/bin/phive
  - phive --version
  - "echo '#### Phing ####'"
  - wget -O /usr/local/bin/phing https://github.com/phingofficial/phing/releases/download/3.0.0-alpha2/phing-3.0.0-alpha2.phar
  - chmod -x /usr/local/bin/phing
  - phing -version

script:
  - phing setup test

cache:
  directories:
    - /home/.cache/composer
    - /home/.phive
