language: "php"

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

before_install:
  - '### https://makandracards.com/aslamk/28305-how-to-change-the-default-gnupg-version-from-gpg-to-gpg2 ###'
  - sudo mv /usr/bin/gpg /usr/bin/gpg1
  - sudo update-alternatives --verbose --install /usr/bin/gpg gnupg /usr/bin/gpg2 50
  - sudo apt-get -y install dirmngr --install-recommends
  - '#### Installing Phive ####'
  - wget -O phive.phar https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar
  - wget -O phive.phar.asc https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/local/bin/phive
  - phive version

install:
  - '#### Installing Phive dependencies ####'
  - phive --no-progress install --force-accept-unsigned --trust-gpg-keys 4AA394086372C20A,8E730BA25823D8B5,2420BAE0A3BE25C6,31C7E470E2138192,CF1A108D0E7AE720
  - '#### Project setup ####'
  - bin/phing setup

before_script:
  - bin/phing cc:before-build

script:
  - bin/phing qa

after_script:
  - bin/phing cc:after-build

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.phive
    - $HOME/.gnupg
