site_name: Case Converter
repo_url: https://github.com/jawira/case-converter
site_author: Jawira Portugal
copyright: MIT
theme:
  name: readthedocs
  highlightjs: true
use_directory_urls: false
strict: true
