@startuml

title Case Converter
skinparam ArrowFontColor Black
skinparam ArrowThickness 2
skinparam UseCaseBackgroundColor #FFFECC
skinparam UseCaseBorderColor #333333
skinparam UseCaseBorderThickness 2
skinparam UseCaseFontColor Black

(help)
(setup)
(qa)
(docs:refresh-images)
(phploc:run)
(composer:validate)
(composer:install-dev)
(phpunit:open-coverage)
(php:lint)
(behat:run)
(phpstan:run)
(phpunit:run)
(phive:install)
(changelog:links)
(cc:get)
(cc:before-build)
(cc:after-build)
(plantuml:puml-to-png)
(git:tags-listing)
(phing:visualize)
(uml-writer:render)
(docs:deploy)
(docs:serve)
(docs:build)
(docs:copy-md)


(setup) -[#5D9CEC]-> (composer:install-dev) : depend:1
(setup) -[#5D9CEC]-> (phive:install) : depend:2
(setup) -[#5D9CEC]-> (cc:get) : depend:3
(qa) -[#5D9CEC]-> (php:lint) : depend:1
(qa) -[#5D9CEC]-> (composer:validate) : depend:2
(qa) -[#5D9CEC]-> (phpunit:run) : depend:3
(qa) -[#5D9CEC]-> (behat:run) : depend:4
(qa) -[#5D9CEC]-> (phpstan:run) : depend:5
(qa) -[#5D9CEC]-> (phploc:run) : depend:6
(docs:refresh-images) -[#5D9CEC]-> (uml-writer:render) : depend:1
(docs:refresh-images) -[#5D9CEC]-> (phing:visualize) : depend:2
(docs:refresh-images) -[#5D9CEC]-> (plantuml:puml-to-png) : depend:3
(phpunit:open-coverage) -[#5D9CEC]-> (phpunit:run) : depend:1
(docs:deploy) -[#5D9CEC]-> (docs:build) : depend:1
(docs:serve) -[#5D9CEC]-> (docs:build) : depend:1
(docs:build) -[#5D9CEC]-> (docs:refresh-images) : depend:1
(docs:build) -[#5D9CEC]-> (docs:copy-md) : depend:2

@enduml
