@startuml
namespace Jawira.CaseConverter  {
	class Convert << class >> {
		#source
		#words
		#forceSimpleCaseMapping
		--
		+__construct()
		+fromAuto()
		#analyse()
		#isUppercaseWord()
		#extractWords()
		+getSource()
		+__call()
		#handleSplitterMethod()
		#createSplitter()
		#handleGluerMethod()
		#createGluer()
		+toArray()
		+forceSimpleCaseMapping()
	}
}
	class Exception << class >> {
	}
Jawira.CaseConverter.CaseConverterException --|> Exception
@enduml

