name: Quality assurance

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        php: [ '7.4','8.0','8.1','8.2','8.3','8.4' ]
    runs-on: ubuntu-24.04
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: xdebug
          tools: phing:v3

      - uses: actions/checkout@v2

      - name: Phing setup
        run: phing setup

      - name: lint php
        run: phing php:lint

      - name: validate composer
        run: phing composer:validate

      - name: behat
        run: phing behat:run

      - name: phpstan
        run: phing phpstan:analyse

      - name: CC before build
        run: phing cc:before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: PHPUnit
        run: phing phpunit:run

      - name: CC after build
        run: phing cc:after-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
